# Generated by Django 4.1.2 on 2023-10-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodDataBankCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BIZUM', 'Bizum'), ('PAYPAL', 'Paypal'), ('BANK_CARD', 'Bank Card')], max_length=10)),
                ('card_number', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('date_of_expire', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodDataBizumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BIZUM', 'Bizum'), ('PAYPAL', 'Paypal'), ('BANK_CARD', 'Bank Card')], max_length=10)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodDataPayPalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BIZUM', 'Bizum'), ('PAYPAL', 'Paypal'), ('BANK_CARD', 'Bank Card')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethodDataBankCard',
        ),
        migrations.DeleteModel(
            name='PaymentMethodDataBizum',
        ),
        migrations.DeleteModel(
            name='PaymentMethodDataPayPal',
        ),
    ]
