# Generated by Django 4.1.2 on 2023-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentmethoddatabankcardmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethoddatabankcardmodel',
            old_name='name',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='paymentmethoddatabizummodel',
            old_name='name',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='paymentmethoddatapaypalmodel',
            old_name='name',
            new_name='payment_method',
        ),
    ]
