# Generated by Django 4.1.2 on 2023-10-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_paymentmethoddatabankcardmodel_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_name', models.CharField(choices=[('BIZUM', 'Bizum'), ('PAYPAL', 'Paypal'), ('BANK_CARD', 'Bank Card')], max_length=10)),
                ('payment_method_data', models.JSONField(default=dict, verbose_name='PaymentMethodData')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=30)),
                ('cvc', models.CharField(max_length=5)),
                ('expiration_date', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethodDataBankCardModel',
        ),
        migrations.DeleteModel(
            name='PaymentMethodDataBizumModel',
        ),
        migrations.DeleteModel(
            name='PaymentMethodDataPayPalModel',
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='core.user'),
        ),
    ]
